apiVersion: v1
kind: ConfigMap
metadata:
  name: user-app-config
  labels:
    name: user-app-config
  namespace: {{ .Values.nameSpace }}
data:
  # property-like keys; each key maps to a simple value
  {{- template "mychart.taskFour" }}
