apiVersion: v1
kind: ConfigMap
metadata:
  name: user-app-config
  labels:
    name: user-app-config
  namespace: {{ .Values.nameSpace }}
data:
  # property-like keys; each key maps to a simple value
  dburl: "jdbc:postgresql://user-db-service:5432/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      app: user-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - image: suleymanbolat/k8slearning:userservice
          name: userservice
          ports:
            - containerPort: 8080
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthCheck
              port: 8080
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 2
            httpGet:
              scheme: HTTP
              path: /healthCheck
              port: 8080
          volumeMounts:
            - name: db-credentials
              mountPath: "/etc/db-credentials"
              readOnly: true
          env:
            - name: dburl
              valueFrom:
                configMapKeyRef:
                  name: user-app-config
                  key: dburl
            - name: dbuser
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      volumes:
        - name: db-credentials
          secret:
            secretName: db-credentials




